# Generated by Django 4.2.7 on 2023-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='preview_image',
            field=models.ImageField(upload_to='event_previews/'),
        ),
    ]
