# Generated by Django 4.2.7 on 2023-12-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
    ]
