# Generated by Django 4.2.7 on 2023-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_events_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='place_images/')),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
