# Generated by Django 4.2.7 on 2023-12-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_created_at_event_user_place_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='astana', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
